name: build

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - "src/frontend/**"
      - "src/backend/**"

jobs:
  build-frontend:
    name: Build and push frontend
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          images: alejoide/instituto-concesionaria-frontend
      - name: Add env files
        run: |
          APP_VERSION=${{ steps.meta-frontend.outputs.version }}
          echo "$FRONTEND_ENV_CONTENT" > ./src/frontend/.env
          echo "APP_VERSION=${APP_VERSION}" >> ./src/frontend/.env
        env:
          FRONTEND_ENV_CONTENT: ${{ secrets.FRONTEND_ENV_CONTENT }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          tags: ${{ steps.meta-frontend.outputs.tags }}
          push: true
          file: ./src/frontend/Dockerfile

  build-backend:
    name: Build and push backend
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          images: alejoide/instituto-concesionaria-backend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend
          tags: ${{ steps.meta-backend.outputs.tags }}
          push: true
          file: ./src/backend/Dockerfile
