name: deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "deploy/**"

jobs:
  deploy:
    name: Deploy to prod
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up project
        run: |
          mkdir -p "$DEPLOY_PATH"
          mkdir -p "$DEPLOY_PATH/config/backend"
          mkdir -p "$DEPLOY_PATH/config/frontend"
          mkdir -p "$DEPLOY_PATH/config/nginx"
          cp -f ./deploy/docker-compose.yaml "$DEPLOY_PATH/docker-compose.yaml"
          APP_VERSION=$(git describe --tags --abbrev=0 || echo "latest")
          echo "$BACKEND_ENV_CONTENT" > "$DEPLOY_PATH/config/backend/.env"
          echo "$FRONTEND_ENV_CONTENT" > "$DEPLOY_PATH/config/frontend/.env"
          echo "APP_VERSION=${APP_VERSION}" >> "$DEPLOY_PATH/config/frontend/.env"
          echo "SERVER_NAME=${APP_URL}" > "$DEPLOY_PATH/config/nginx/.env"
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          BACKEND_ENV_CONTENT: ${{ secrets.BACKEND_ENV_CONTENT }}
          FRONTEND_ENV_CONTENT: ${{ secrets.FRONTEND_ENV_CONTENT }}
          # No esta en los secretos, esta en las variables
          APP_URL: ${{ vars.APP_URL }}
      - name: Pull changes and restart
        run: |
          cd "${{ secrets.DEPLOY_PATH }}"
          docker compose down --remove-orphans
          docker compose pull
          docker compose up -d
